export urlWebextTeams=https://api.ciscospark.com/v1/messages
export botToken=NWQ0OWRlYjItNzJkZi00MDMyLTllYjYtNWMxNzBhOTkzODIzNTgyNGNkYWQtMzU1
export idRoomTodos=Y2lzY29zcGFyazovL3VzL1JPT00vODFjNzc4ZjAtMzNlZC0xMWU5LWI5ZTMtZmRiMmI3ODM2MGI4
export idRoomYo=Y2lzY29zcGFyazovL3VzL1JPT00vYzE4NjU4MGItZjU0NC0zMzllLThjYjItYWVhMzJhNDcxNDli
 
export urlSMS=https://rest.nexmo.com/sms/json
export sender=INER-t
export api_key=19868339
export api_secret=u4gdopqbTdxav4lM